/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as AuthorizedImport } from './routes/_authorized'
import { Route as IndexImport } from './routes/index'
import { Route as AuthorizedProfileImport } from './routes/_authorized/profile'
import { Route as AuthorizedDashboardImport } from './routes/_authorized/dashboard'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthorizedRoute = AuthorizedImport.update({
  id: '/_authorized',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthorizedProfileRoute = AuthorizedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthorizedRoute,
} as any)

const AuthorizedDashboardRoute = AuthorizedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthorizedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authorized': {
      preLoaderRoute: typeof AuthorizedImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_authorized/dashboard': {
      preLoaderRoute: typeof AuthorizedDashboardImport
      parentRoute: typeof AuthorizedImport
    }
    '/_authorized/profile': {
      preLoaderRoute: typeof AuthorizedProfileImport
      parentRoute: typeof AuthorizedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthorizedRoute.addChildren([
    AuthorizedDashboardRoute,
    AuthorizedProfileRoute,
  ]),
  AuthRoute,
])

/* prettier-ignore-end */
